---
# tasks file for roles/grafana


  tasks:
    - name: Installer Grafana Alloy
    - shell: |
      ARCH={{ arch }} \
      GCLOUD_HOSTED_METRICS_URL={{ gcloud_hosted_metrics_url }} \
      GCLOUD_HOSTED_METRICS_ID={{ gcloud_hosted_metrics_id }} \
      GCLOUD_SCRAPE_INTERVAL={{ gcloud_scrape_interval }} \
      GCLOUD_HOSTED_LOGS_URL={{ gcloud_hosted_logs_url }} \
      GCLOUD_HOSTED_LOGS_ID={{ gcloud_hosted_logs_id }} \
      GCLOUD_RW_API_KEY={{ gcloud_rw_api_key }} \
      /bin/sh -c "$(curl -fsSL {{ install_script_url }})"
    args:
      executable: /bin/bash

  - name: Append Grafana Config
    template:
      src: grafana.ini.j2
      dest: /etc/alloy/grafana.ini
    notify:
      - restart grafana

  - name: Restart Alloy service
    tasks:
      - name: Restart alloy.service using systemd
        ansible.builtin.systemd:
          name: alloy.service
          state: restarted
