---
# tasks file for roles/grafana

- name: Install Alloy
  ansible.builtin.shell: |
    export DEBIAN_FRONTEND=noninteractive
    ARCH="amd64" \
    GCLOUD_HOSTED_METRICS_URL="https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push" \
    GCLOUD_SCRAPE_INTERVAL="60s" \
    GCLOUD_HOSTED_LOGS_URL="https://logs-prod-012.grafana.net/loki/api/v1/push" \
    GCLOUD_HOSTED_METRICS_ID="{{ grafana_metrics_id }}" \
    GCLOUD_HOSTED_LOGS_ID="{{ grafana_logs_id }}" \
    GCLOUD_RW_API_KEY="{{ grafana_cloud_api_key }}" \
    /bin/sh -c "$(curl -fsSL https://storage.googleapis.com/cloud-onboarding/alloy/scripts/install-linux.sh)"
  become: yes

- name: Append content of config.alloy to /etc/alloy/config.alloy
  ansible.builtin.blockinfile:
    path: /etc/alloy/config.alloy
    block: "{{ lookup('file', 'files/config.alloy') }}"
    marker: "// {mark} ANSIBLE MANAGED BLOCK"
  become: yes

- name: Restart Alloy service
  systemd:
    name: alloy
    state: restarted
    enabled: yes
  when: ansible_facts['os_family'] == 'Debian'
  become: yes
