---
# tasks file for roles/rippled

# Installation
- name: Install required utilities
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - wget
      - gnupg
    state: present
    update_cache: true
  become: true
  tags:
    - install

- name: Ensure the directory keyrings exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags:
    - install

- name: Download the ripple GPG key
  get_url:
    url: https://repos.ripple.com/repos/api/gpg/key/public
    dest: /tmp/ripple_public_key.gpg
    mode: '0644'
  tags:
    - install

- name: Convert the GPG key to the format required by APT
  command: >
    gpg --dearmor -o /etc/apt/keyrings/ripple.gpg /tmp/ripple_public_key.gpg
  args:
    creates: /etc/apt/keyrings/ripple.gpg
  tags:
    - install

- name: Remove the temporary GPG key file
  file:
    path: /tmp/ripple_public_key.gpg
    state: absent
  tags:
    - install

- name: Get OS release name
  ansible.builtin.shell: lsb_release -cs | tail -n1
  register: os_release
  changed_when: false
  tags:
    - install

- name: Add ripple repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/ripple.gpg] https://repos.ripple.com/repos/rippled-deb {{ os_release.stdout | trim }} stable"
    state: present
    filename: ripple
  become: true
  tags:
    - install

- name: Install rippled
  apt:
    name: rippled
    state: present
    update_cache: true
  become: true
  tags:
    - install

- name: Configure rippled - Copy custom rippled.cfg
  copy:
    src: ./files/rippled.cfg
    dest: /etc/opt/ripple/rippled.cfg
    owner: root
    group: root
    mode: '0644'
  become: yes
  tags:
    - install

- name: Copy validators.txt
  copy:
    src: ./files/validators.txt
    dest: /etc/opt/ripple/validators.txt
    owner: root
    group: root
    mode: '0644'
  become: yes
  tags:
    - install

- name: Restart rippled to apply the new configuration
  service:
    name: rippled
    state: restarted
    enabled: yes
  tags:
    - install

- name: Ensure rippled is started
  service:
    name: rippled
    state: started
    enabled: yes
  tags:
    - install

# Uninstallation
- name: Stop rippled
  service:
    name: rippled
    state: stopped
  become: true
  tags:
    - uninstall

- name: Remove rippled package
  apt:
    name: rippled
    state: absent
  become: true
  tags:
    - uninstall

- name: Remove ripple GPG key
  file:
    path: /etc/apt/keyrings/ripple.gpg
    state: absent
  become: true
  tags:
    - uninstall

- name: Remove keyrings directory
  file:
    path: /etc/apt/keyrings
    state: absent
  become: true
  tags:
    - uninstall

- name: Remove keyrings directory
  file:
    path: /etc/apt/sources.list.d/ripple.list
    state: absent
  become: true
  tags:
    - uninstall

- name: Remove rippled configuration files
  file:
    path: /etc/opt/ripple
    state: absent
  become: true
  tags:
    - uninstall